[package]

name = "hematite"
version = "0.0.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
tags = []

[profile.release]
opt-level = 2
debug = false

[[bin]]

name = "hematite"
path = "src/main.rs"

[dependencies]
byteorder = "0.3"
mmap = "0.1"
flate2 = "0.2"
libc = "*"
rustc-serialize = "0.3"
time = "*"
fps_counter = "0.2.0"
camera_controllers = "0.10.0"
vecmath = "0.2.0"
image = "0.5.0"
sdl2 = "0.10.0"
shader_version = "0.2.0"
piston = "0.15.1"
pistoncore-sdl2_window = "0.18.0"
gfx = "0.8.0"
gfx_device_gl = "0.7.0"
piston3d-gfx_voxel = "0.5.0"
