[package]

name = "hematite"
version = "0.0.0"
readme = "README.md"
authors = ["bvssvni <bvssvni@gmail.com>"]
tags = []

[[bin]]

name = "hematite"
path = "src/main.rs"

[dependencies.piston]

git = "https://github.com/PistonDevelopers/piston"

[dependencies.graphics]

git = "https://github.com/PistonDevelopers/rust-graphics"

[dependencies.opengl_graphics]

git = "https://github.com/PistonDevelopers/opengl_graphics"

[dependencies.sdl2_game_window]

git = "https://github.com/PistonDevelopers/sdl2_game_window"

[dependencies.hgl]

git = "https://github.com/cmr/hgl-rs"

[dependencies.gl]

git = "https://github.com/bjz/gl-rs"

