[package]

name = "hematite"
version = "0.0.8"
license = "MIT"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["minecraft", "piston", "client"]
description = "A simple Minecraft client"
repository = "https://github.com/PistonDevelopers/hematite.git"
homepage = "http://hematite.piston.rs"

[profile.release]
opt-level = 2
debug = false

[[bin]]

name = "hematite"
path = "src/main.rs"

[dependencies]
byteorder = "0.4.2"
camera_controllers = "0.11.0"
docopt = "0.6.78"
flate2 = "0.2.13"
fps_counter = "0.2.0"
gfx = "0.9.1"
gfx_device_gl = "0.8.2"
image = "0.6.1"
libc = "0.2.7"
memmap = "0.2.3"
piston = "0.18.0"
piston3d-gfx_voxel = "0.7.0"
pistoncore-sdl2_window = "0.25.0"
rustc-serialize = "0.3.18"
shader_version = "0.2.1"
time = "0.1.34"
vecmath = "0.2.0"
zip = "0.1.16"
