[package]

name = "hematite"
version = "0.0.0"
readme = "README.md"
authors = ["bvssvni <bvssvni@gmail.com>"]
tags = []

[[bin]]

name = "hematite"
path = "src/main.rs"

[dependencies.piston]

git = "https://github.com/pistondevelopers/piston/"

[dependencies.graphics]

git = "https://github.com/pistondevelopers/rust-graphics"

[dependencies.opengl_graphics]

git = "https://github.com/pistondevelopers/opengl_graphics"

[dependencies.sdl2_game_window]

git = "https://github.com/pistondevelopers/sdl2_game_window"

[dependencies.hgl]

git = "https://github.com/cmr/hgl-rs/"


