[package]

name = "hematite"
version = "0.0.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
tags = []

[profile.dev]
opt-level = 2
debug = false

[profile.release]
opt-level = 2
debug = false

[[bin]]

name = "hematite"
path = "src/main.rs"

[dependencies.piston]

git = "https://github.com/PistonDevelopers/piston"

[dependencies.sdl2_game_window]

git = "https://github.com/PistonDevelopers/sdl2_game_window"

[dependencies.cgmath]

git = "https://github.com/bjz/cgmath-rs"

[dependencies.gfx]

git = "https://github.com/gfx-rs/gfx-rs"
