[package]

name = "hematite"
version = "0.0.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
tags = []

[profile.release]
opt-level = 2
debug = false

[[bin]]

name = "hematite"
path = "src/main.rs"

[dependencies]
byteorder = "0.3"
mmap = "0.1"
flate2 = "0.2"
libc = "*"
rustc-serialize = "0.3"
time = "*"
fps_counter = "0.0.2"
camera_controllers = "0.1"
vecmath = "0.1"
image = "0.3"
sdl2 = "0.4"
shader_version = "0.1"
pistoncore-input = "0.1"
pistoncore-event = "0.1"
pistoncore-window = "0.1"
pistoncore-sdl2_window = "0.2"
gfx = "0.6"
gfx_device_gl = "0.4"
piston3d-gfx_voxel = "0.0.5"
