[package]

name = "hematite-client"
version = "0.0.1"
authors = ["bvssvni <bvssvni@gmail.com>"]
tags = []

[profile.release]
opt-level = 2
debug = false

[[bin]]

name = "hematite"
path = "src/main.rs"

[dependencies]
byteorder = "0.3"
camera_controllers = "0.10.0"
docopt = "0.6.76"
flate2 = "0.2"
fps_counter = "0.2.0"
gfx = "0.8.0"
gfx_device_gl = "0.7.0"
image = "0.5.0"
libc = "*"
memmap = "0.2.2"
piston = "0.16.0"
piston3d-gfx_voxel = "0.5.0"
pistoncore-sdl2_window = "0.20.0"
rustc-serialize = "0.3"
sdl2 = "0.11.0"
shader_version = "0.2.0"
time = "*"
vecmath = "0.2.0"
zip = "0.1.14"
