[package]

name = "hematite"
version = "0.0.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
tags = []

[profile.dev]
opt-level = 2
debug = false

[profile.release]
opt-level = 2
debug = false

[[bin]]

name = "hematite"
path = "src/main.rs"

[dependencies.gfx_voxel]

git = "https://github.com/PistonDevelopers/gfx_voxel"

[dependencies.cam]

git = "https://github.com/PistonDevelopers/cam"

[dependencies.fps_counter]

git = "https://github.com/PistonDevelopers/fps_counter"

[dependencies.vecmath]

git = "https://github.com/PistonDevelopers/vecmath"

[dependencies.image]

git = "https://github.com/PistonDevelopers/image"

[dependencies.sdl2_window]

git = "https://github.com/PistonDevelopers/sdl2_window"

[dependencies.cgmath]

git = "https://github.com/bjz/cgmath-rs"

[dependencies.gfx]

git = "https://github.com/gfx-rs/gfx-rs"
